[package]
name = "tip"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
